# Generated by Django 2.0.6 on 2018-11-27 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('prj_code', models.CharField(default='testing', max_length=100, verbose_name='项目内部代号')),
                ('status', models.CharField(choices=[('计划中', '计划中'), ('进行中', '进行中'), ('分析中', '分析中'), ('已结束', '已结束'), ('其他', '其他')], max_length=10, verbose_name='项目状态')),
                ('starttime', models.DateField(max_length=12, verbose_name='开始日期')),
                ('endtime', models.DateField(max_length=12, verbose_name='结束日期')),
                ('linkurl', models.CharField(default='#', max_length=50, verbose_name='项目地址')),
                ('description', models.TextField(verbose_name='项目介绍')),
                ('relusers', models.ManyToManyField(related_name='myprojects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '流调项目',
                'ordering': ('id', 'name'),
            },
        ),
    ]
