# Generated by Django 2.0.6 on 2018-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj001', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='person_born',
        ),
        migrations.AddField(
            model_name='other',
            name='born_pougongchan',
            field=models.BooleanField(default=False, verbose_name='剖宫产'),
        ),
        migrations.AddField(
            model_name='other',
            name='born_yindaofenmian',
            field=models.BooleanField(default=False, verbose_name='阴道分娩'),
        ),
        migrations.AddField(
            model_name='other',
            name='born_zaochan',
            field=models.BooleanField(default=False, verbose_name='早产'),
        ),
        migrations.AddField(
            model_name='other',
            name='born_zuyuechan',
            field=models.BooleanField(default=False, verbose_name='足月产'),
        ),
    ]
