# Generated by Django 2.0.6 on 2018-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj001', '0002_auto_20181129_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='pastpreg_pougong',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='剖宫产次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_qinggongshu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='清宫术次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_renliu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='人工流产次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_shenghuarenshen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='生化妊娠次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_shunchan',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='顺产次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_taitingyu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='胎停育次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_yaoliu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='药物流产次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_yiweirenshen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='异位妊娠次数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_yuncount',
            field=models.CharField(max_length=20, verbose_name='孕次总数'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pastpreg_ziranliu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='自然流产次数'),
        ),
    ]
