# Generated by Django 2.0.6 on 2018-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj001', '0003_auto_20181129_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='accessory_quanxuexibaojishu',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='全血细胞计数'),
        ),
    ]
